### ISSUE TITLE
<substitute> with an unrecognized type crashes the whole document

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetML#1870]
## Summary

`<substitute>` with a `type` it does not recognize throws `TypeError: undefined is not a function` during core initialization, so the whole document fails to render rather than the one component degrading.

## Reproducer

```xml
<substitute type="banana" match="x" replacement="y">x+1</substitute>
```

The document does not render; the core reports `undefined is not a function`.

Both conditions are needed. An unrecognized `type` **and** `match`/`replacement` present:

| Document | Result |
| --- | --- |
| `<substitute type="banana" match="x" replacement="y">x+1</substitute>` | **crash** |
| `<substitute type="banana" match="x" replacement="y"><math>x+1</math></substitute>` | **crash** |
| `<substitute type="banana" match="x" replacement="y"><text>x+1</text></substitute>` | **crash** |
| `<substitute type="BANANA" match="x" replacement="y">x+1</substitute>` | **crash** |
| `<substitute type="banana">x+1</substitute>` | ok |
| `<substitute type="math" match="x" replacement="y">x+1</substitute>` | ok |
| `<substitute type="text" match="x" replacement="y">x+1</substitute>` | ok |
| `<substitute match="x" replacement="y">x+1</substitute>` | ok |

## Cause

**Two fallbacks disagree about what an unrecognized `type` means**, because one reads the raw attribute string and the other reads the validated state variable.

- `Substitute.js:24-41` declares `type` with `defaultPrimitiveValue: "math"` and `validValues: ["math", "text"]`. `validateAttributeValue` rejects `banana` and falls back to **`math`**, so `stateValues.type` is `math`.
- `match` and `replacement` are `_componentWithSelectableType` (`Substitute.js:43-54`). That component resolves its type from `parentAttributes.type?.value` — the **raw** `banana`, before validation — and its own guard (`ComponentWithSelectableType.js:41-53`) falls back to **`number`**, warning `doenet-w0016`.

So the `type === "math"` branch runs over `match`/`replacement` children that were built as `<number>`. `Substitute.js:323` then calls `dependencyValues.match.subscripts_to_strings()`, which a number does not have.

Stack:

```
TypeError: undefined is not a function
    at Object.definition (src/components/Substitute.js:323:49)
    at StateVariableEvaluator.getStateVariableValue (src/core/StateVariableEvaluator.ts:170:34)
    at Substitute.createSerializedReplacements (src/components/Substitute.js:520:29)
    at expandCompositeComponent (src/core/CompositeExpander.ts:352:18)
```

Note that `Substitute.js:136-139` (`addType`, the sugar path) guards this correctly and independently, falling back to `math` from the raw value — so the sugar and the attribute children already disagree too. Any fix should probably make one reading authoritative rather than adding a third guard.

## Suggested direction

Not prescriptive, but the shapes that look plausible: have `_componentWithSelectableType` inherit the parent's *validated* type rather than the raw attribute, or have `<substitute>` reject an unrecognized `type` up front the way `<chart type>` and `<sampleMultivariateRandomNumber type>` do (a warning plus doing nothing) instead of silently substituting `math`.

Whatever the fix, a document should never fail to render because one attribute value is misspelled.

## Notes

- **Pre-existing**, not introduced by #1869. Verified by checking `src/core/StateVariableDefinitionFactory.ts` out from `main` (the only file on this path that #1869 touches), re-running, and observing the identical crash.
- Found while reviewing #1869; out of scope there.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
